### ISSUE TITLE
Failed to start SLURM snap on CentOS7

### ISSUE THREAD

**Issue by niklasmelin** [omnivector-solutions/snap-slurm#107]
[root@penny-c59 ~]# journalctl -x -u snap.slurm.mysql.service
-- Logs begin at Wed 2020-09-16 08:17:29 UTC, end at Wed 2020-09-16 08:43:13 UTC. --
Sep 16 08:36:51 penny-c59.maas.rnd.scania.com systemd[1]: Started Service for snap application slurm.mysql.
-- Subject: Unit snap.slurm.mysql.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit snap.slurm.mysql.service has finished starting up.
-- 
-- The start-up result is done.
Sep 16 08:36:51 penny-c59.maas.rnd.scania.com systemd[1]: snap.slurm.mysql.service: main process exited, code=exited, status=1/FAILURE
Sep 16 08:36:51 penny-c59.maas.rnd.scania.com systemd[1]: Unit snap.slurm.mysql.service entered failed state.
Sep 16 08:36:51 penny-c59.maas.rnd.scania.com systemd[1]: snap.slurm.mysql.service failed.
Sep 16 08:37:27 penny-c59.maas.rnd.scania.com systemd[1]: Started Service for snap application slurm.mysql.
-- Subject: Unit snap.slurm.mysql.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit snap.slurm.mysql.service has finished starting up.
-- 
-- The start-up result is done.
Sep 16 08:37:28 penny-c59.maas.rnd.scania.com slurm.mysql[10831]: 2020-09-16T08:37:28.562716Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server 
Sep 16 08:37:28 penny-c59.maas.rnd.scania.com slurm.mysql[10831]: 2020-09-16T08:37:28.865498Z 0 [Warning] InnoDB: New log files created, LSN=45790
Sep 16 08:37:28 penny-c59.maas.rnd.scania.com slurm.mysql[10831]: 2020-09-16T08:37:28.908257Z 0 [Warning] InnoDB: Creating foreign key constraint system tables.
Sep 16 08:37:28 penny-c59.maas.rnd.scania.com slurm.mysql[10831]: 2020-09-16T08:37:28.963251Z 0 [Warning] No existing UUID has been found, so we assume that this is the first time that this server has been start
Sep 16 08:37:28 penny-c59.maas.rnd.scania.com slurm.mysql[10831]: 2020-09-16T08:37:28.963610Z 0 [Warning] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
Sep 16 08:37:29 penny-c59.maas.rnd.scania.com slurm.mysql[10831]: 2020-09-16T08:37:29.236666Z 0 [Warning] CA certificate ca.pem is self signed.
Sep 16 08:37:29 penny-c59.maas.rnd.scania.com slurm.mysql[10831]: 2020-09-16T08:37:29.322948Z 1 [Warning] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecur
Sep 16 08:37:30 penny-c59.maas.rnd.scania.com slurm.mysql[10831]: NEW INSTALL
Sep 16 08:37:31 penny-c59.maas.rnd.scania.com slurm.mysql[10831]: Starting MySQL. ERROR! The server quit without updating PID file (/var/snap/slurm/common/var/run/mysql/mysql.pid).
Sep 16 08:37:31 penny-c59.maas.rnd.scania.com systemd[1]: snap.slurm.mysql.service: main process exited, code=exited, status=1/FAILURE
Sep 16 08:37:31 penny-c59.maas.rnd.scania.com systemd[1]: Unit snap.slurm.mysql.service entered failed state.
Sep 16 08:37:31 penny-c59.maas.rnd.scania.com systemd[1]: snap.slurm.mysql.service failed.
Sep 16 08:42:36 penny-c59.maas.rnd.scania.com systemd[1]: Started Service for snap application slurm.mysql.
-- Subject: Unit snap.slurm.mysql.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit snap.slurm.mysql.service has finished starting up.
-- 
-- The start-up result is done.
Sep 16 08:42:36 penny-c59.maas.rnd.scania.com slurm.mysql[13170]: 2020-09-16T08:42:36.345495Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server 
Sep 16 08:42:36 penny-c59.maas.rnd.scania.com slurm.mysql[13170]: 2020-09-16T08:42:36.346124Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
Sep 16 08:42:36 penny-c59.maas.rnd.scania.com slurm.mysql[13170]: 2020-09-16T08:42:36.346138Z 0 [ERROR] Aborting
Sep 16 08:42:36 penny-c59.maas.rnd.scania.com slurm.mysql[13170]: NOT NEW INSTALL
Sep 16 08:42:37 penny-c59.maas.rnd.scania.com slurm.mysql[13170]: Starting MySQL. ERROR! The server quit without updating PID file (/var/snap/slurm/common/var/run/mysql/mysql.pid).
Sep 16 08:42:37 penny-c59.maas.rnd.scania.com systemd[1]: snap.slurm.mysql.service: main process exited, code=exited, status=1/FAILURE
Sep 16 08:42:37 penny-c59.maas.rnd.scania.com systemd[1]: Unit snap.slurm.mysql.service entered failed state.
Sep 16 08:42:37 penny-c59.maas.rnd.scania.com systemd[1]: snap.slurm.mysql.service failed.
lines 1-48/48 (END)

[root@penny-c59 mysql]# uname -a
Linux penny-c59.maas.rnd.scania.com 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[root@penny-c59 mysql]# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

[root@penny-c59 mysql]# cat /etc/redhat-release 
CentOS Linux release 7.8.2003 (Core)
[root@penny-c59 mysql]# snap list
Name    Version  Rev   Tracking       Publisher             Notes
core20  20       634   latest/stable  canonical✓            base
slurm   20.02.1  319   20.02/edge     omnivector-solutions  classic
snapd   2.46.1   9279  latest/stable  canonical✓            snapd
[root@penny-c59 mysql]#

**Comment by jamesbeedy** [comment]
Hey @niklasmelin, thanks for reporting this! Closing because we have disabled the use of mysql inside of the snap.
