### ISSUE TITLE
Document addition needed: How do I stop it after the instalation

### ISSUE THREAD

**Issue by laszewsk** [omnivector-solutions/snap-slurm#109]
I like to start and stop the slurm services with snap. 

What is the command to start them and to stop them.

Could you please add a section to your documentation?

My use case is:

a) activate Slurm
b) run 100+ jobs on my computer leveraging my cores to run them in parallel
c) deactivate slurm 

Then once I do a new experiment I return to a) and do it over again.

**Comment by ducks23** [comment]
@laszewsk you just need to stop the service if you are running the slurmdbd daemon you would do `sudo service snap.slurm.slurmdbd stop'

**Comment by jamesbeedy** [comment]
hey @laszewsk, you can install the slurm snap from the snapstore and set the `snap.mode` configuration value to`all`.

So your process would be:

a ) Install slurm and set `snap.mode` to classic
```bash
sudo snap install slurm --classic
sudo snap set slurm snap.mode=all
```
You can see what services are running with the command:
```bash
$ sudo snap services slurm
Service           Startup   Current   Notes
slurm.logrotate   disabled  inactive  timer-activated
slurm.munged      enabled   active    -
slurm.slurmctld   enabled   active    -
slurm.slurmd      enabled   active    -
slurm.slurmdbd    enabled   inactive  -
slurm.slurmrestd  enabled   active    -
```
b) Run your jobs
```bash
sinfo/sbatch/srun
```
c) Set the `snap.mode` to `none` to deactivate the slurm processes.
```bash
sudo snap set slurm snap.mode=none
```

See that no processes are active:
```bash
$ sudo snap services slurm
Service           Startup   Current   Notes
slurm.logrotate   disabled  inactive  timer-activated
slurm.munged      enabled   inactive  -
slurm.slurmctld   enabled   inactive  -
slurm.slurmd      enabled   inactive  -
slurm.slurmdbd    enabled   inactive  -
slurm.slurmrestd  enabled   inactive  -
```

Let us know if you need any other help out!

Thanks!
