### ISSUE TITLE
What to install on clients?

### ISSUE THREAD

**Issue by tbarbette** [omnivector-solutions/snap-slurm#120]
Hi! Thanks for this package, it works great for the master node. However it's unclear what to install on "clients" nodes. I only need munge right? How to pass the key?

**Comment by heitorPB** [comment]
Hi!

This snap is deployed with https://github.com/omnivector-solutions/slurm-charms. We have some basic documentation [here](https://omnivector-solutions.github.io/osd-documentation/master/) on how to deploy.

On your compute nodes, you should have the snap mode set to `slurmd`.

Munge 0.5.14 is included in this snap.

**Comment by tbarbette** [comment]
Thanks! But that looks a bit more large-scale to use charms. I did manage to make it work, the key being to set mode to slurmd as you suggested. Then manually copy the key. 

Shall I do a PR to to explain this example master/node configuration? Or is that out of scope?

**Comment by heitorPB** [comment]
Glad to hear that! How many compute nodes you have?

PRs are very welcome!

**Comment by tbarbette** [comment]
We have 30 machines in our research team. However we'll slowly migrate from google spreadsheet allocation to slurm. One problem is we're a network research team and slurm has nothing to handle the wiring of machines, eg which machines are connected to which constraining the allocation. So we'll start by explicitely allocating whole nodes.

**Comment by jamesbeedy** [comment]
hey @tbarbette , thanks for your interest in the slurm snap!

Possibly we can hop on a call and walk through a demo of how we are deploying it. Let us know if you are interested!

**Comment by heitorPB** [comment]
> we have 100G cables connected back-to-back, or through a switch

I'm curious about this! Are you experimenting with new network topologies? Is it similar to Dragonfly? It's been a while I don't read about advances in networks, is 100G already possible on cooper?

I'll leave this issue open, feel free to ask us if you any questions.

**Comment by tbarbette** [comment]
@jamesbeedy Thanks but we'll take things slowly. I think we have what we need for now.
@heitorPB not really. We work in high speed networking, inter-server load balancing (Cheetah at NSDI'20), intra-server load-balancing (RSS++ at CoNEXT'19), NFV in general (Metron, NSDI'18) so we need in general one machine to generate traffic, one to do the processing. Sometimes more.  To study topologies, we would need many many machines, I've only seen simulations (NS3 etc). One reason we moved to slurm is to allow co-locating these simulations when we don't use the machines as they don't require NICs and wiring.
It would be nice to have a slurm plugin that link the 100G interface of allocated nodes through some VLAN. But for us it's not worth the development time.
