### ISSUE TITLE
slurm_load_partitions: Unable to contact slurm controller (connect failure)

### ISSUE THREAD

**Issue by miikargh** [omnivector-solutions/snap-slurm#24]
Hi,

The command `slurm.sinfo` returns the following:

```bash
slurm_load_partitions: Unable to contact slurm controller (connect failure)
```

I ran the following commands prior:
```bash
$ sudo snap install slurm
$ sudo snap connect slurm:network-control
$ sudo snap set slurm snap.mode=all
```

The command `slurm.scontrol ping` returns:
```bash
Slurmctld(primary) at pop-os is DOWN
```

Environment info:
```bash
$ snap --version
snap    2.44.3+20.04
snapd   2.44.3+20.04
series  16
pop     20.04
kernel  5.4.0-7626-generic
```

What should I do to fix this?

**Comment by egee-irl** [comment]
Hi there -

I tried reproducing the issue with the stable branch on a fresh VM and wasn't able to.

Could you post a gist of the output of this command? `journalctl -eu snap.slurm.*`?

Thanks for the helpful debugging info!

**Comment by egee-irl** [comment]
I fixed this today; there should be a new build on the Edge channel very shortly. Feel free to try it and report back.

Also as a workaround for the issue, you can simply restart slurmctld like so - `systemctl restart snap.slurm.slurmctld`.

**Comment by miikargh** [comment]
Works now, thanks a thousand!
