### ISSUE TITLE
slurmstepd error: couldn't change dir to /home/cloud-user

### ISSUE THREAD

**Issue by jamesbeedy** [omnivector-solutions/snap-slurm#40]
After a fresh install on centos8, I run the srun command and get this error:

<img width="619" alt="Screen Shot 2020-06-05 at 5 48 58 AM" src="https://user-images.githubusercontent.com/5590546/83878864-9d068200-a6f1-11ea-9d93-c641b836656f.png">

**Comment by egee-irl** [comment]
I believe this has been fixed for some time now. Closing.
