### ISSUE TITLE
slurmrestd: JWT plugin not available

### ISSUE THREAD

**Issue by erik78se** [omnivector-solutions/snap-slurm#42]
Trying to use SLURM with JWT.

Following this guide from SchedMD official docs: https://slurm.schedmd.com/jwt.html

- Modified "slurm.conf" as described in the docs.
- Restarted slurmctld as described in the docs.

.... after restarting slurmctld as described in the docs.
cat /var/snap/slurm/common/var/log/slurm/slurmctld.log, errors are shown.

[2020-06-08T21:07:59.542] debug3: Trying to load plugin /snap/slurm/current/lib/slurm/auth_jwt.so
[2020-06-08T21:07:59.542] debug4: /snap/slurm/current/lib/slurm/auth_jwt.so: Does not exist or not a regular file.
[2020-06-08T21:07:59.542] error: Couldn't find the specified plugin name for auth/jwt looking at all files
[2020-06-08T21:07:59.545] error: cannot find auth plugin for auth/jwt
[2020-06-08T21:07:59.545] error: cannot create auth context for auth/jwt
[2020-06-08T21:07:59.545] fatal: failed to initialize authentication plugin

**Comment by jamesbeedy** [comment]
@erik78se pretty sure this is a non issue, although I wanted you to verify. Feel free to close this out if non-issue. Thanks!

**Comment by erik78se** [comment]
I would like to understand this jwt thing better first.

For example, scontrol can do stuff here.

But generally, understanding the jwt tool as such.

Den lör 13 juni 2020 02:10jamesbeedy <notifications@github.com> skrev:

**Comment by jamesbeedy** [comment]
@erik78se this is an issue and we are currently looking into it. I'll report back here when we have something in the works to fix this.

**Comment by pawr** [comment]
I would be interested in the progress on this as well. I have had successful implementations on centos7. Working on a test branch to see if I can get it implemented, however I am a bit new to snap builds.

**Comment by pawr** [comment]
Would it be possible to provide a method or resource for installing from the this specific branch? I didn't see it as an available channel.

**Comment by jamesbeedy** [comment]
we build the slurm snap with libjwt [here](https://github.com/omnivector-solutions/snap-slurm/blob/develop/snap/snapcraft.yaml#L218,L229) and [here](https://github.com/omnivector-solutions/snap-slurm/blob/develop/snap/snapcraft.yaml#L163)
