### ISSUE TITLE
When using snap in a lxd container it leaks between instances

### ISSUE THREAD

**Issue by erik78se** [omnivector-solutions/snap-slurm#43]
When running two instances of lxd containers "slurm" and "slurm2":
Then, when testing the slurmrestd, it seems to get into a conflicting situation where the second instance (slurm2) produce data in the first (slurm).

This might be a natural consequence of snap/lxd, but never the less a bug?

======= Below history of my test ==============

root@slurm2:/tmp# slurm.squeue 
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON) 

root@slurm2:/tmp# slurm.sacct
       JobID    JobName  Partition    Account  AllocCPUS      State ExitCode 
------------ ---------- ---------- ---------- ---------- ---------- -------- 
2              hostname      debug       root          1  COMPLETED      0:0 
3              hostname      debug       root          1  COMPLETED      0:0 

root@slurm2:/tmp# vi jobrun.py 
root@slurm2:/tmp# python3 jobrun.py 
Status code:  200
Printing Post JSON data
{'errors': [], 'job_id': 19, 'step_id': 'BATCH', 'job_submit_user_msg': ''}

root@slurm2:/tmp# slurm.sinfo 
PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST 
debug*       up   infinite      1   idle slurm2 

root@slurm2:/tmp# slurm.squeue 
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON) 

root@slurm2:/tmp# slurm.sinfo 
PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST 
debug*       up   infinite      1   idle slurm2 
root@slurm2:/tmp# slurm.srun -pdebug -n1 -l hostname
0: slurm2

root@slurm2:/tmp# slurm.sinfo 
PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST 
debug*       up   infinite      1   idle slurm2 
root@slurm2:/tmp# slurm.sacct
       JobID    JobName  Partition    Account  AllocCPUS      State ExitCode 
------------ ---------- ---------- ---------- ---------- ---------- -------- 
2              hostname      debug       root          1  COMPLETED      0:0 
3              hostname      debug       root          1  COMPLETED      0:0 
4              hostname      debug       root          1  COMPLETED      0:0 
root@slurm2:/tmp# exit
logout
erik@iceberg:~$ lxc shell slurm
mesg: ttyname failed: No such device
root@slurm:~# ls
demo  nodes.sh  slurm  snap  submittest.sh  t.json  t.py  t.sh  t1.py  test.sh
root@slurm:~# python3 t1.py 
Status code:  200
Printing Post JSON data
{'errors': [], 'job_id': 20, 'step_id': 'BATCH', 'job_submit_user_msg': ''}

**Comment by erik78se** [comment]
Update: It seems that this behaviour is replicated even without a single instance. The below screenshot shows the situation.

![Screenshot from 2020-06-09 15-01-39](https://user-images.githubusercontent.com/850603/84150488-391de980-aa62-11ea-99f3-c687bdff90bf.png)

**Comment by jamesbeedy** [comment]
Closing this for now. Feel free to reopen if this bug reappears. Thanks!
