### ISSUE TITLE
slurmrestd inaccurate API definition

### ISSUE THREAD

**Issue by NilesDev** [omnivector-solutions/snap-slurm#58]
This turned out to be pretty big, we may want to split this. Also, not sure what's inherent from slurm and what we can change. 

The API definition gained from GET /openapi (and the other 3 variations) has some issues:

- /openapi.yaml returns JSON format. 

- .../job/submit POST requestBody: the object requested by submit should contain both job_properties (named "job") and a field called "script".
 
- job_properties schema: 
  - some listed properties are not recognized by slurmrestd:
    - argv
    - cpu_binding_hint
    - kill_on_invalid_dependency
    - mcs_label
    - time_minimum
  - some listed properties have typos:
    - cluster_constraints (should be cluster_constraint)
    - standard_in (...input)
    - standard_out (...output)

- results of sending certain properties:
  - hold: confirmation that the job is held is in an error message?
  - get_user_environment: claims to accept boolean, actually accepts integer 1/0
  - wait_all_nodes: claims to accept boolean, actually accepts integers (can be higher than 1)
  - no_kill: claims to accept boolean, actually accepts the string "off" (no other strings I tried were valid, including "on")
  - nice: claims to accept strings, actually accepts integers and strings that can be parsed as integers
  - memory_per_node: seems to only accept 0 and 1? Proper error message for negative integers, but non-specific error for values of 2+. (Other "memory_per_*" properties work fine.)
  - open_mode: claims to accept enum, actually accepts any string (as far as I could see)
  - tasks_per_socket: seems to not validate, accepts negative numbers.

Properties in general: 
requesting unavailable resources (more than the cluster can deliver) the answer is often the super generic error code -1. Can be hard for users to interpret. 
Exceptions: thread_specification, tasks_per_node and cpus_per_task give good feedback. (Though with a typo: "cpus per task much be greater than 0".)

**Comment by jamesbeedy** [comment]
@NilesDev thanks for reporting. Going to close this as it is out of scope of the slurm snap itself.
