### ISSUE TITLE
slurmrestd default disabled properties?

### ISSUE THREAD

**Issue by NilesDev** [omnivector-solutions/snap-slurm#59]
In stock installation, "user_id" and "group_id" are disabled in slurmrestd.  
All jobs submitted through the restd are then performed by "snap_daemon" which could run into some permission issues.

**Comment by NilesDev** [comment]
Same in classic mode, except actions are taken by "root" instead of "snap_daemon".

**Comment by egee-irl** [comment]
> In stock installation, "user_id" and "group_id" are disabled in slurmrestd.

_Disabled_ sounds like something that is configurable. Slurmrestd does not use a handy configuration file the way Slurmd does - is there a known way to deploy this with user and group id's enabled?

**Comment by jamesbeedy** [comment]
@NilesDev thanks for reporting this. The slurm snap now runs in `--classic` confinement mode which should have solved this issue.  Closing for now but, feel free to reopen if this issues still exists for you. Thanks!
