### ISSUE TITLE
Cant find /usr/bin/srun when running STARCCM+ through slurm

### ISSUE THREAD

**Issue by erik78se** [omnivector-solutions/snap-slurm#67]
I'm trying to run STARCCM throug the latest build.

STARCCM version: 14.06.012

```salloc -p debug -n1```

#!/bin/bash

START_MACRO="./starccmSim.java"
CDLMD_LICENSE_FILE="27012@license-server.com"
STAR_CLASS_PATH="/some/path/to/software/Java/poi-3.7-FINAL"
LOG_FILE="starccmSim.log"
START_DIR=${SLURM_SUBMIT_DIR}
WORK_DIR=${START_DIR}
END_DIR=${START_DIR}

SIM_FILE=SteadyFlowBackwardFacingStep_final.sim

EXE=/share/apps/cd-adapco/RHEL5/14.06.012/STAR-CCM+14.06.012/star/bin/starccm+

SLURM_TASKS_PER_NODE=40
SLURM_NTASKS=40

NODE_FILE="nodelist_${JOB_NAME}"

/some/path/to/software/hostlist/python-hostlist-1.18/hostlist --append=: --append-slurm-tasks=$SLURM_TASKS_PER_NODE -e $SLURM_JOB_NODELIST >  $NODE_FILE

$EXE -machinefile ${NODE_FILE} -power -np $SLURM_NTASKS -batch ${START_MACRO} -classpath ${STAR_CLASS_PATH} -mpi intel -mpiflags '-bootstrap slurm' ${SIM_FILE} &>> ${LOG_FILE}

sssler@n-c72$ $EXE -machinefile ${NODE_FILE} -power -np $SLURM_NTASKS -batch ${START_MACRO} -classpath ${STAR_CLASS_PATH} -mpi intel -mpiflags '-bootstrap slurm' ${SIM_FILE}
Starting local server: /share/apps/cd-adapco/RHEL5/14.06.012/STAR-CCM+14.06.012/star/bin/starccm+ -machinefile nodelist_ -power -np 40 -mpi intel -mppflags "-bootstrap slurm" -server -rsh ssh SteadyFlowBackwardFacingStep_final.sim
[mpiexec@n-c72] HYDU_create_process (../../utils/launch/launch.c:825): execvp error on file /usr/bin/srun (No such file or directory)
^C[mpiexec@n-c72] Sending Ctrl-C to processes as requested
[mpiexec@n-c72] HYDU_sock_write (../../utils/sock/sock.c:418): write error (Bad file descriptor)
[mpiexec@n-c72] Press Ctrl-C again to force abort
[mpiexec@n-c72] HYD_pmcd_pmiserv_send_signal (../../pm/pmiserv/pmiserv_cb.c:253): unable to write data to proxy
[mpiexec@n-c72] ui_cmd_cb (../../pm/pmiserv/pmiserv_pmci.c:175): unable to send signal downstream
[mpiexec@n-c72] HYDT_dmxu_poll_wait_for_event (../../tools/demux/demux_poll.c:76): callback returned error status
[mpiexec@n-c72] HYD_pmci_wait_for_completion (../../pm/pmiserv/pmiserv_pmci.c:507): error waiting for event
[mpiexec@n-c72] main (../../ui/mpich/mpiexec.c:1148): process manager error waiting for completion

Running on Ubuntu18.04 although the installation is for RHEL/centos

**Comment by egee-irl** [comment]
So my initial thought was to symlink the Slurm commands straight into `/usr/bin/` but that did not work because of how Snap exec's the user commands.

What does work is placing a wrapper script in `/usr/bin` that simply calls the Slurm command in `/snap/bin`. A very simple implementation of this would be:

```
#!/bin/bash

exec "/snap/bin/slurm.srun" "$@"
```

Place this script here: `/usr/bin/srun` and then `chmod +x /usr/bin/srun`. The STARCCM should find its way to the correct binary.

**Comment by egee-irl** [comment]
The demo today looked good and since the wrapper shim fixed it, I think I'm going to close this for now.

Making the fix permanent would be a provisioning/Juju task since the Snap itself can't really control how starccm invokes Slurm commands
