### ISSUE TITLE
Document on how to create a N node cluster

### ISSUE THREAD

**Issue by erik78se** [omnivector-solutions/snap-slurm#71]
I don't know how to create a N node cluster at the moment.

E.g. how to distribute the slurm.conf and munge-key.

SLURM is useless in a single node setup, so having a very clear and easy path to change/modify slurm.conf and slurm.conf.d is critical.

**Comment by molanjingke** [comment]
Hi, have you ever found the method of creating multi-computer cluster? It also confuses me now.

**Comment by molanjingke** [comment]
> Hi, have you ever found the method of creating multi-computer cluster? It also confuses me now.

The configure of slurm from ubuntu pacakge or source code is pretty easy, but it  works not well here by just simply editing "slurm.conf".

**Comment by egee-irl** [comment]
> The configure of slurm from ubuntu pacakge or source code is pretty easy, but it works not well here by just simply editing "slurm.conf".

Have you tried configuring the slurm.conf located at `/var/snap/slurm/common/etc/`?

**Comment by jamesbeedy** [comment]
Hey @erik78se and @molanjingke thanks for using snap-slurm.

To configure the slurm snap, you can modify the `slurm.conf` file in `/var/snap/slurm/common/etc/slurm/slurm.conf`. Just issue the `scontrol reconfigure` command to ensure the changes are picked up by the cluster. In the case you apply changes to the `slurm.conf` that cannot be applied by `scontrol` you can restart the slurm processes using systemd.
```bash
for service in slurmctld slurmd slurmrestd; do
    sudo service snap.slurm.$service restart
 done
```
We have started documentation on using the slurm-charms [here](https://omnivector-solutions-osd-documentation.readthedocs-hosted.com/en/latest/), which would be the fastest way to getting a multi-node cluster up and running. Feel free to contribute to the documentation for the slurm charms by creating an issue/feature/pull request on the [slurm charms documentation repository](https://github.com/omnivector-solutions/osd-documentation).

Thanks!

**Comment by molanjingke** [comment]
@jamesbeedy @egee-irl Thanks a lot for your kindness and reply. 
At that momentom, I was pretty confused about the `/var/snap/slurm/common/etc/slurm-configurator/slurm.yaml` file which is a tool for persistent changes to the Slurm configuration files while `slurm.conf or slurmdbd.conf will be overwritten when the snap.mode is changed`. As a result, the original function of `slurm.conf or slurmdbd.conf` was ignored.
Thank you again for your projects. Without your work, our life won't be so convenient.
