### ISSUE TITLE
Performance settings for large clusters etc.

### ISSUE THREAD

**Issue by erik78se** [omnivector-solutions/snap-slurm#73]
The snap or juju should take care of setting a number of performance related parameters documented here: https://slurm.schedmd.com/big_sys.html

Primarily, make sure that the "login node" has the proper ulimits set since this is PROPAGATED to the slurmd processes.

So, if you have low ulimits on the login-node, this will impact also the jobs.

**Comment by egee-irl** [comment]
I'll add this to the documentation but this is a provisioning concern and not something the Snap can control. @jamesbeedy

**Comment by erik78se** [comment]
Good thing.
