### ISSUE TITLE
When moved ubuntu home, cant issue snap commands

### ISSUE THREAD

**Issue by erik78se** [omnivector-solutions/snap-slurm#76]
Ubuntu user cant issue slurm commands

ubuntu@n-c72:$ ls
aliases  slurm_20.02.1_amd64_classic.snap  snap
ubuntu@n-c72:$ mdkir t

Command 'mdkir' not found, did you mean:

  command 'mdir' from deb mtools
  command 'mkdir' from deb coreutils

Try: sudo apt install <deb name>

ubuntu@n-c72:$ mkdir t
ubuntu@n-c72:$ cd t/
ubuntu@n-c72:/t$ sinfo 
cannot create user data directory: /lhome/ubuntu/snap/slurm/x1: Permission denied
ubuntu@n-c72:/t$

**Comment by jamesbeedy** [comment]
Going to close this for now @erik78se . Let us know if you see it again. Thanks!
