### ISSUE TITLE
missing command "unmunge" prevents testing of communication of munge.

### ISSUE THREAD

**Issue by erik78se** [omnivector-solutions/snap-slurm#78]
As per the installation for munge: https://github.com/dun/munge/wiki/Installation-Guide

$ slurm.munge -n | unmunge

Command 'unmunge' not found, but can be installed with:

snap install slurm  # version 20.02.1, or
apt  install munge

See 'snap info slurm' for additional versions.

**Comment by erik78se** [comment]
I have a two node cluster with 40 cores each.

Submitting a job with -n80 as:

srun -n80 -p debug hostname

ssler@n-c72:/cluster/sesonas13/sssler/startests/small$ srun -n80 hostname
srun: error: Task launch for 47.0 failed on node n-c122: Invalid job credential
srun: error: Application launch failed: Invalid job credential
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
n-c72
n-c72
n-c72
n-c72
n-c72
n-c72
n-c72
n-c72
n-c72
n-c72
n-c72
n-c72
n-c72
n-c72
n-c72
n-c72
n-c72
n-c72
n-c72
n-c72
n-c72
n-c72
n-c72
n-c72
n-c72
n-c72
n-c72
n-c72
n-c72
n-c72
n-c72
slurmstepd: error: *** STEP 47.0 ON n-c72 CANCELLED AT 2020-07-04T14:40:39 ***
n-c72
n-c72
n-c72
n-c72
n-c72
n-c72
n-c72
n-c72
n-c72

**Comment by egee-irl** [comment]
I verified we support `unmunge` via [this](https://github.com/omnivector-solutions/snap-slurm/commit/68c2bbfc94d1f59da070b28ff7d5a46175f496e3) changeset. However, it is only supported in the **classic** Snap at this time.

I installed the latest classic Snap on mytest VM and tried it:

```
root@slurminv3:~/snap-slurm# slurm.munge -n | slurm.unmunge
STATUS:          Success (0)
ENCODE_HOST:     slurminv3 (127.0.1.1)
ENCODE_TIME:     2020-07-07 19:32:16 +0000 (1594150336)
DECODE_TIME:     2020-07-07 19:32:16 +0000 (1594150336)
TTL:             300
CIPHER:          aes128 (4)
MAC:             sha256 (5)
ZIP:             none (0)
UID:             root (0)
GID:             root (0)
LENGTH:          0
```

Until we are able to get the Classic Snap into the Snap store, all commands must be namespaced, unfortunately.

**Comment by erik78se** [comment]
Perfect. No problem with that namespace atm
