### ISSUE TITLE
snap cant write data even on local disk

### ISSUE THREAD

**Issue by erik78se** [omnivector-solutions/snap-slurm#81]
I've logged in as ubuntu and is located on a local disk home "/lhome/ubuntu"

Even so, I get this permission denied when trying basic slurm commands.

ubuntu@n-c122:~$ slurm.sinfo 
cannot create user data directory: /lhome/ubuntu/snap/slurm/x1: Permission denied
ubuntu@n-c122:~$

**Comment by egee-irl** [comment]
Alternate home directories are not supported out of the box with Snapd. It can be _unofficially_ supported during provisioning with Juju using an alleged workaround.

I requested more details about the workaround here - https://forum.snapcraft.io/t/alternate-home-workaround-request/18679

**Comment by erik78se** [comment]
I left a comment in there.

**Comment by jamesbeedy** [comment]
Closing this as we use classic mode now. Thanks all!
