### ISSUE TITLE
NHC gets a  AVC apparmor="DENIED" 

### ISSUE THREAD

**Issue by erik78se** [omnivector-solutions/snap-slurm#84]
journalctl -xe | grep DENIED

Jul 09 12:04:52 n-c122 audit[29569]: AVC apparmor="DENIED" operation="file_inherit" profile="/snap/snapd/8140/usr/lib/snapd/snap-confine" name="/var/snap/slurm/common/var/log/nhc/nhc.log" pid=29569 comm="snap-confine" requested_mask="a" denied_mask="a" fsuid=0 ouid=0
Jul 09 12:04:52 n-c122 kernel: audit: type=1400 audit(1594296292.233:1710): apparmor="DENIED" operation="file_inherit" profile="/snap/snapd/8140/usr/lib/snapd/snap-confine" name="/var/snap/slurm/common/var/log/nhc/nhc.log" pid=29569 comm="snap-confine" requested_mask="a" denied_mask="a" fsuid=0 ouid=0
Jul 09 12:05:22 n-c122 audit[29609]: AVC apparmor="DENIED" operation="file_inherit" profile="/snap/snapd/8140/usr/lib/snapd/snap-confine" name="/var/snap/slurm/common/var/log/nhc/nhc.log" pid=29609 comm="snap-confine" requested_mask="a" denied_mask="a" fsuid=0 ouid=0
Jul 09 12:05:22 n-c122 kernel: audit: type=1400 audit(1594296322.325:1711): apparmor="DENIED" operation="file_inherit" profile="/snap/snapd/8140/usr/lib/snapd/snap-confine" name="/var/snap/slurm/common/var/log/nhc/nhc.log" pid=29609 comm="snap-confine" requested_mask="a" denied_mask="a" fsuid=0 ouid=0

Seems like something Node Health Check for slurm is hitting

**Comment by egee-irl** [comment]
This is happening because NHC is running from within the Snap but being called by a forked process that winds up being outside the Snap. It's probably fixable by changing the way that slurmd calls NHC.

**Comment by jamesbeedy** [comment]
We have decoupled nhc to its own charm/snap that run in classic mode for many reasons , but one was definitely to fix this issue. Closing this as the issue doesn't exist anymore. Thanks!
