### ISSUE TITLE
provisoning some security params

### ISSUE THREAD

**Issue by erik78se** [omnivector-solutions/snap-slurm#85]
On ubuntu systems, this removes warnings on ptrace issues for mpi

sudo vim /etc/sysctl.d/10-ptrace.conf

kernel.yama.ptrace_scope = 0

Still trying to get infiniband starccm jobs running on ubuntu with the snap.

**Comment by egee-irl** [comment]
@jamesbeedy This could be something we perform during Juju provisioning?

**Comment by jamesbeedy** [comment]
@erik78se thanks for reporting this. As @egee-irl correctly stated, this is something we can look at configuring through the use of charms - add-on style charms that do application specific tuning outside of the slurm snap. Going to close the issue and use it as reference in case the issue ever comes up again. Thanks again.
