### ISSUE TITLE
srun: Unable to create step for job 10: Error generating job credential

### ISSUE THREAD

**Issue by erik78se** [omnivector-solutions/snap-slurm#96]
-bash-4.2$ srun -N 1 --pty bash
2020/07/24 07:31:43.238903 cmd_run.go:409: restoring default SELinux context of /home/erik/snap
srun: error: Unable to create step for job 10: Error generating job credential
-bash-4.2$ 

-bash-4.2$ slurm.version 
2020/07/24 07:32:34.807255 cmd_run.go:409: restoring default SELinux context of /home/erik/snap
20.02.1

**Comment by jamesbeedy** [comment]
@erik78se thanks for reporting this. Going to close the issue as we believe the problem has been addressed. Please reopen if you see anything of this nature again. Thanks!
